### ISSUE TITLE
Maybe make it a template?

### ISSUE THREAD

**Issue by HippoBaguette** [pomber/stargazer#3]
Instead of everyone forking this repo if they want to use it, could you make it a template?

**Comment by junhoyeo** [comment]
How about deploying the workflow as a GitHub App? This way we can easily add the action to an existing repository 👍

**Comment by yashash1511** [comment]
it would be very nice if this could be made into a reusable github action. Which we can run on a schedule to auto update the stargazers video for our project.

**Comment by yashash1511** [comment]
```yaml
on:
  workflow_dispatch:
    inputs:
      repoOrg:
        description: Repo Org
        required: true
        default: yashash1511
      repoName:
        description: Repo Name
        required: true
        default: win11Svelte
      starCount:
        description: Star Count
        required: true
        default: 35
      duration:
        description: Duration (seconds)
        required: false
        default: 5
name: Render video
jobs:
  render:
    name: Render video
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          repository: pomber/stargazer
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - name: Install dependencies (ffmpeg and fonts)
        run: |
          sudo apt-get update -yqq
          sudo apt-get install -yq --no-install-recommends \
            ffmpeg \
            fonts-noto-core fonts-noto-cjk fonts-noto-color-emoji fonts-noto-mono
      - name: Install dependencies (node modules)
        run: npm i
      - name: Inject configurations
        run: echo $WORKFLOW_INPUT | tee input-props.json | jq -C '.'  # Inject to file, inspect to logs
        env:
          WORKFLOW_INPUT: ${{ toJson(github.event.inputs) }}
      - name: Render video
        run: npm run build -- --props="./input-props.json"
        env:
          REMOTION_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload video
        uses: actions/upload-artifact@v3
        with:
          name: out.mp4
          path: out.mp4
      - name: Checkout
        uses: actions/checkout@main
      - run: rm -f out.mp4
      - uses: actions/download-artifact@v3
        with:
          name: out.mp4
      - run: |
          git config --global user.email github-actions[bot]@users.noreply.github.com
          git config --global user.name github-actions[bot]
          git add .
          git commit -m "Updated Stargazers Video"
          git push
```
